### ISSUE TITLE
Custom actions.

### ISSUE THREAD

**Issue by eddiezab** [pixolith/fabricjs-customise-controls-extension#12]
Currently custom actions are limited to those predetermined by the extension. I would like to be able to set the actions to utilize functions/callbacks to better integrate with applications.

For example: 
`mr: {
                            action: function(ev, target) {console.log(ev, target);},                            
                            cursor: 'crosshair'
                        }
`

**Comment by MDSLKTR** [comment]
Hey there. That sounds like an interesting feature. Would you like to have a go at implementing this and submitting a PR? Otherwise i currently cannot give a timeframe currently when i have the time to code it. I would be supporting as good as i can though.

The key entry point would probably be checking in _setupCurrentTransform if the action is a function and then returning the proper values for you to use instead of calling an internal function.

**Comment by eddiezab** [comment]
So I'm not a JS developer, and just hack it when I need to, so I don't know how to deal with making the minified version for a pull request and what not. I did accomplish what I was looking for right in the _setupCurrentTransform, and just added the following:

``` javascript
            if ( typeof action === 'function' ) {
                action( e, target );
            }

```

**Comment by MDSLKTR** [comment]
well yeah, that should be it i guess haha. Let me get this in and release a new version

**Comment by MDSLKTR** [comment]
you should be able to use this now if you bump your version to 0.1.2.
