### ISSUE TITLE
Can't remove the top most rotate handle

### ISSUE THREAD

**Issue by ghost** [pixolith/fabricjs-customise-controls-extension#26]
I can get it to work, but I don't want the native rotate handle to appear because I want to control rotation from another handle.

**Comment by MDSLKTR** [comment]
Hello,

have you tried?
````
this.setControlsVisibility({
    tr: false, // top right
});

**Comment by craziduezi** [comment]
Hi there, great customisation extension for fabricjs! I had a quick question though. I'm originally setting the customised options when I initiate the canvas. Giving the objects all the same customised controls. The issue is that when I add an image (new fabric.Image) and try to change the controls; I'm able to set the custom icons for the Image but the actions still is inherited from the general settings.

```
 `video1.customiseCornerIcons({
    settings: {
        borderColor: 'black',
        cornerSize: 25,
        cornerShape: 'rect',
        cornerBackgroundColor: 'black',
        cornerPadding: 10
    },
    br: {
        icon: '/upload/fabric-svgs/up.svg'
    }
});

video1.customiseControls({
    br: {
        action: function( e, target ) {
            console.log(e, target);
        }
     }
});`
```
The actual error I'm receiving from console is "Uncaught TypeError: video1.customizeControls is not a function". 

*note - This note from your README.md ```
fabric.Object.prototype.customiseCornerIcons
fabric.Canvas.prototype.customiseControls
``` 
It makes me think it's just a general setting and would need to extended to each individual object.  Anyways I appreciate the help in advance and again love the extension!

**Comment by MDSLKTR** [comment]
Close since no update regarding this issue.
