### ISSUE TITLE
Custom actions on mouse move

### ISSUE THREAD

**Issue by artboard-studio** [pixolith/fabricjs-customise-controls-extension#30]
Hi

First of all thank you very much for this great extension, but I am confused a little bit about using custom actions.

For my shapes, I would like to use custom actions so that when I click and drag the 4 corner controls it would change the width and the height of the shape instead of scaling it, but it appears to me that the only event that I have access to when using custom actions is `mouse:down` (click).

Is there any way to have access to mouse move?

**Comment by MDSLKTR** [comment]
Hey there,
first of all, thanks for the question. I appreciate any feedback i can get. Concerning your question, i think two problems arise. One would be that fabric.js currently is limited to actions being defined in the canvas context instead of the object context. This means you won't be able to define actions for each object.
Fortunatly there is one workaround [here](https://github.com/pixolith/fabricjs-customise-controls-extension/issues/28) which allows you do this on an event basis. Secondly i don't think you will be able to overwrite the mouse functions bound to the corners as only resize allows you actually drag the object.

However did you try using a simple standard resize to scale up the object and on mouse:up calculating the new width and height by the original w/h multiplied by the scale values? Afterwards you could set the scale back to 1 and the object has a new width and height.

**Comment by artboard-studio** [comment]
Thank you very much for your thorough answer. I will certainly give the workaround a try.

Yes, it's a possible solution to scale and then set the width and height based on that. I also need the `mouse:move` event for other functionalities too, for example for my rectangle shapes I want to dedicate one of the corners to border radius, use clicks and drags and sets the border radius based on that. With the workaround, it might become a bit hacky so to speak, but I hope I can make it work none the less.

**Comment by MDSLKTR** [comment]
Hey again,

yeah that would be a possible solution. It's gonna be a bit hacky for sure. Also for the border radius you could utilize the scale as well i think. Use the current scale value from the canvas scale event as an indicator for the border radius but fixate the current scaleX/scaleY from the fabric object to the initial values.

**Comment by artboard-studio** [comment]
Thank you very much for the help, Simon 👍

**Comment by MDSLKTR** [comment]
Closed because of inactivity. Please re-open for further help :)
