### ISSUE TITLE
Remove action not working on i-text element

### ISSUE THREAD

**Issue by simsationX** [pixolith/fabricjs-customise-controls-extension#35]
Hi 

Thank you for this awesome project.

Unfortunately the remove action does not work properly on an i-text element. If I click on the remove icon which triggers the remove action the following error message appears:

`Uncaught TypeError: Cannot read property 'getPointer' of undefined`

So I began to write my own remove method:

```
action: function(e, target) { 
  target.off();
  target.remove();
  setTimeout( function() {
    canvas.deactivateAll();
  }, 0 );
}
```

The important thing is to call target.off() first. This way it works for a single i-text object. It took me some hours to get that.

Maybe you could fix this in your remove action, as well if there is a group of i-text objects?

Simon

**Comment by MDSLKTR** [comment]
Hey there,

thank you for reporting this. This sounds like it was a nasty thing to find and fix. I shall adapt your fix very soon and release a new version. Good Stuff!

Simon

**Comment by MDSLKTR** [comment]
fixed in: https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.2.2

**Comment by fsanano** [comment]
Also I find this bug, when I create group with image and IText. My group don't delete, just lost focus this group.

**Comment by MDSLKTR** [comment]
@fsanano hey there, which fabricjs version are you using and is there any error in the console?

**Comment by fsanano** [comment]
I use v0.3.5. 
But yesterday i fix this bug: 
```javascript
action: (e, target) => {
  target.off()
  setTimeout(() => {
   canvas.deactivateAll()
   canvas.remove(target)
  }, 0)
}
```

**Comment by SmboBeast** [comment]
For what it is worth, @fsanano's fix worked for me as well.  

I was having an issue with things not deleting as well using the standard action: 'remove' snippet.

I then went ahead with overriding the action method with my own function.  I basically just did the below, and things sort of worked.  I say sort of, because the actual target object wasn't removed immediately when the remove corner button was clicked.  Instead, only when the canvas was repainted, the layer would disappear.

`
action: function( e, target ) {
            canvas.remove(target);
            canvas.renderAll();
          },
`
@fsanano's workaround actually made it work better.   Thanks for that.

I would like to understand why things were acting up though.  If you have a minute, I'd love to learn.

**Comment by MDSLKTR** [comment]
@SmboBeast I basicly put the above fix into the default remove action. I'm not quite sure why this was needed. I can only assume that clicking the remove corner would immediately trigger another click action which would activate the image again and therefore maybe not remove it in the same render. Using the setTimeout 0 hack forces it into the next render cycle which makes it work as expected. Certainly not pretty but in the new version of fabric (2.x) this workaround isn't necessary anymore.
