### ISSUE TITLE
Custom icon position

### ISSUE THREAD

**Issue by arturmagalhaesjr** [pixolith/fabricjs-customise-controls-extension#53]
Hi,

I have tried to change the default position of custom icons, so when I changed the position of one element, that's OK, but the mouse interaction area remains wrong.

That area stay the same even changing the icon position.

Example:

``` js
// top-left
this._drawControl('tl', ctx, methodName,
   left + MARGIN_CORNER,
   top + MARGIN_CORNER,
   this.tlIcon,
   this.tlSettings
);
```
How do you think that I can fix this ?

Thanks a lot.

**Comment by MDSLKTR** [comment]
Hey there,

thank you for your Question. This is sadly a very difficult topic since the mouse interaction areas as you described are not bound to the plain drawing areas of the corner which you shifted with your `MARGIN_CORNER` value.
This has been discussed here: https://github.com/pixolith/fabricjs-customise-controls-extension/issues/22
It also features a fork of this repo (i hope it still exists) where it was successfully implemented. The reason it is not in this repository is, that i find adding this feature to be too invasive towards the core functionality. It requires a bunch of stuff that then needs to be updated when fabric is updated. I kinda want to keep the overloading of functions to a minimum in order to make updates easier.

Regards and Good Luck :),
Simon
