### ISSUE TITLE
Controls outside the canvas

### ISSUE THREAD

**Issue by nitin-bc** [pixolith/fabricjs-customise-controls-extension#58]
Hi.

Is it possible to have controls for any object outside the canvas?

**Comment by MDSLKTR** [comment]
Hey,

at the moment not possible due to limitations in fabric.js and how the controls are built. It would be way to much workaround in order to get it working.
This has been done and discussed here: https://github.com/pixolith/fabricjs-customise-controls-extension/issues/22
Maybe you can find something useful in there.

Regards,
Simon
